[package]
name = "rodio"
version = "0.3.2"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "Apache-2.0"
description = "Audio playback library"
keywords = ["audio", "playback", "gamedev"]
repository = "https://github.com/tomaka/rodio"
documentation = "http://tomaka.github.io/rodio/rodio/index.html"

[dependencies]
cpal = { git = "https://github.com/tomaka/cpal", branch = "futures" }
futures = { git = "https://github.com/alexcrichton/futures-rs" }
hound = "1.0.0"
lazy_static = "0.1.12"
time = "0.1.32"
vorbis = "0.0.14"
