[package]
name = "rodio"
version = "0.3.2"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
license = "Apache-2.0"
description = "Audio playback library"
keywords = ["audio", "playback", "gamedev"]
repository = "https://github.com/tomaka/rodio"
documentation = "http://tomaka.github.io/rodio/rodio/index.html"

[dependencies]
cpal = "0.3.0"
futures = "0.1.0"
hound = "1.0.0"
lazy_static = "0.1.12"
vorbis = "0.0.14"
